Refine build and reporting

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,22 +12,67 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Install and Init Opam
-        id: setup-opam
-        run: |
-          sudo apt-get install --no-install-recommends opam
-          opam init --disable-sandboxing -y
-          opam switch create 5.2.0+ox --repos ox=git+https://github.com/oxcaml/opam-repository.git,default
-
       - name: Initialize Report
-        if: steps.setup-opam.outcome == 'success'
         run: |
           echo "# Build Status Report" > README.md
           echo "Run Date: $(date)" >> README.md
           echo "" >> README.md
 
+      - name: Install opam
+        id: install-opam
+        run: |
+          CMD="sudo apt-get install --no-install-recommends opam"
+          echo "## Command: \`$CMD\`" >> README.md
+          echo "\`\`\`" >> README.md
+          if $CMD; then
+            echo "Status: SUCCESS" >> README.md
+            echo "\`\`\`" >> README.md
+            echo "" >> README.md
+          else
+            echo "Status: FAILURE" >> README.md
+            echo "\`\`\`" >> README.md
+            echo "" >> README.md
+            exit 1
+          fi
+
+      - name: Init opam
+        id: init-opam
+        if: steps.install-opam.outcome == 'success'
+        run: |
+          CMD="opam init --disable-sandboxing -y"
+          echo "## Command: \`$CMD\`" >> README.md
+          echo "\`\`\`" >> README.md
+          if $CMD; then
+            echo "Status: SUCCESS" >> README.md
+            echo "\`\`\`" >> README.md
+            echo "" >> README.md
+          else
+            echo "Status: FAILURE" >> README.md
+            echo "\`\`\`" >> README.md
+            echo "" >> README.md
+            exit 1
+          fi
+
+      - name: Create Switch
+        id: oxcaml-switch
+        if: steps.init-opam.outcome == 'success'
+        run: |
+          CMD="opam switch create 5.2.0+ox --repos ox=git+https://github.com/oxcaml/opam-repository.git,default"
+          echo "## Command: \`$CMD\`" >> README.md
+          echo "\`\`\`" >> README.md
+          if $CMD; then
+            echo "Status: SUCCESS" >> README.md
+            echo "\`\`\`" >> README.md
+            echo "" >> README.md
+          else
+            echo "Status: FAILURE" >> README.md
+            echo "\`\`\`" >> README.md
+            echo "" >> README.md
+            exit 1
+          fi
+
       - name: Install ocamlformat
-        if: steps.setup-opam.outcome == 'success'
+        if: steps.oxcaml-switch.outcome == 'success'
         run: |
           eval $(opam env)
           CMD="opam install -y ocamlformat"
@@ -42,7 +87,7 @@ jobs:
           echo "" >> README.md
 
       - name: Install merlin
-        if: steps.setup-opam.outcome == 'success'
+        if: steps.oxcaml-switch.outcome == 'success'
         run: |
           eval $(opam env)
           CMD="opam install -y merlin"
@@ -57,7 +102,7 @@ jobs:
           echo "" >> README.md
 
       - name: Install ocaml-lsp-server
-        if: steps.setup-opam.outcome == 'success'
+        if: steps.oxcaml-switch.outcome == 'success'
         run: |
           eval $(opam env)
           CMD="opam install -y ocaml-lsp-server"
@@ -72,7 +117,7 @@ jobs:
           echo "" >> README.md
 
       - name: Install utop
-        if: steps.setup-opam.outcome == 'success'
+        if: steps.oxcaml-switch.outcome == 'success'
         run: |
           eval $(opam env)
           CMD="opam install -y utop"
@@ -87,7 +132,7 @@ jobs:
           echo "" >> README.md
 
       - name: Install parallel
-        if: steps.setup-opam.outcome == 'success'
+        if: steps.oxcaml-switch.outcome == 'success'
         run: |
           eval $(opam env)
           CMD="opam install -y parallel"
@@ -102,7 +147,7 @@ jobs:
           echo "" >> README.md
 
       - name: Install core-unix
-        if: steps.setup-opam.outcome == 'success'
+        if: steps.oxcaml-switch.outcome == 'success'
         run: |
           eval $(opam env)
           CMD="opam install -y core-unix"
